//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cave.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cave.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name,Template,Reference
        ///1d-interleaved-parityfec,application/1d-interleaved-parityfec,[RFC6015]
        ///3gpdash-qoe-report+xml,application/3gpdash-qoe-report+xml,[_3GPP][Ozgur_Oyman]
        ///3gpp-ims+xml,application/3gpp-ims+xml,[John_M_Meredith]
        ///A2L,application/A2L,[ASAM][Thomas_Thomsen]
        ///activemessage,application/activemessage,[Ehud_Shapiro]
        ///activemessage,application/activemessage,[Ehud_Shapiro]
        ///alto-costmap+json,application/alto-costmap+json,[RFC7285]
        ///alto-costmapfilter+json,application/alto-costmapfilter+json,[R [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string application {
            get {
                return ResourceManager.GetString("application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name,Template,Reference
        ///1d-interleaved-parityfec,audio/1d-interleaved-parityfec,[RFC6015]
        ///32kadpcm,audio/32kadpcm,[RFC3802][RFC2421]
        ///3gpp,audio/3gpp,[RFC3839][RFC6381]
        ///3gpp2,audio/3gpp2,[RFC4393][RFC6381]
        ///ac3,audio/ac3,[RFC4184]
        ///AMR,audio/AMR,[RFC4867]
        ///AMR-WB,audio/AMR-WB,[RFC4867]
        ///amr-wb+,audio/amr-wb+,[RFC4352]
        ///aptx,audio/aptx,[RFC7310]
        ///asc,audio/asc,[RFC6295]
        ///ATRAC-ADVANCED-LOSSLESS,audio/ATRAC-ADVANCED-LOSSLESS,[RFC5584]
        ///ATRAC-X,audio/ATRAC-X,[RFC5584]
        ///ATRAC3,audio/ATRAC3,[RFC5584]
        ///basic,a [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [MSG::Welcome]
        ///&lt;html&gt;
        ///&lt;p&gt;Hello $NickName,&lt;/p&gt;
        ///&lt;p&gt;we welcome you to the CaveSystems GmbH services.&lt;/p&gt;
        ///&lt;p&gt;You registered for a new account bound to the email address $EmailAddress (you are currently receiving this mail at).&lt;/p&gt;
        ///&lt;p&gt;If you want to validate the account and activate it please use the following link: &lt;a href=&quot;$Server/VerifyEmail?email=$EmailAddress&amp;amp;code=$Code&quot;&gt;Verification Link&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If the link does not work for some reason you can go to &lt;a href=&quot;$Server/Verify&quot;&gt;$Server/Verify&lt;/a&gt; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string AuthMessages {
            get {
                return ResourceManager.GetString("AuthMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css&quot; integrity=&quot;sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ&quot; crossorigin=&quot;anonymous&quot;&gt;
        ///&lt;script src=&quot;https://code.jquery.com/jquery-3.1.1.slim.min.js&quot; integrity=&quot;sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js&quot; integrity=&quot;sha384-DztdAPBWPRX [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string CaveWebServerHeaders {
            get {
                return ResourceManager.GetString("CaveWebServerHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name,Template,Reference
        ///collection,font/collection,[RFC8081]
        ///otf,font/otf,[RFC8081]
        ///sfnt,font/sfnt,[RFC8081]
        ///ttf,font/ttf,[RFC8081]
        ///woff,font/woff,[RFC8081]
        ///woff2,font/woff2,[RFC8081]
        /// ähnelt.
        /// </summary>
        public static string font {
            get {
                return ResourceManager.GetString("font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name,Template,Description,Reference
        ///bmp,image/bmp,,[RFC7903]
        ///cgm,image/cgm,Computer Graphics Metafile,[Alan_Francis]
        ///dicom-rle,image/dicom-rle,,[DICOM_Standards_Committee][David_Clunie]
        ///emf,image/emf,,[RFC7903]
        ///example,image/example,,[RFC4735]
        ///fits,image/fits,,[RFC4047]
        ///g3fax,image/g3fax,,[RFC1494]
        ///gif,,,[RFC2045][RFC2046]
        ///ief,,Image Exchange Format,[RFC1314]
        ///jls,image/jls,,[DICOM_Standards_Committee][David_Clunie]
        ///jp2,image/jp2,,[RFC3745]
        ///jpeg,,,[RFC2045][RFC2046]
        ///jpm,image/jpm,,[RFC3745]
        ///jpx [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name,Template,Reference
        ///CPIM,message/CPIM,[RFC3862]
        ///delivery-status,message/delivery-status,[RFC1894]
        ///disposition-notification,message/disposition-notification,[RFC8098]
        ///example,message/example,[RFC4735]
        ///external-body,,[RFC2045][RFC2046]
        ///feedback-report,message/feedback-report,[RFC5965]
        ///global,message/global,[RFC6532]
        ///global-delivery-status,message/global-delivery-status,[RFC6533]
        ///global-disposition-notification,message/global-disposition-notification,[RFC6533]
        ///global-headers,message/global-header [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name,Template,Reference
        ///3mf,model/3mf,[http://www.3mf.io/specification][_3MF][Michael_Sweet]
        ///example,model/example,[RFC4735]
        ///gltf+json,model/gltf+json,[Khronos][Uli_Klumpp]
        ///iges,model/iges,[Curtis_Parks]
        ///mesh,,[RFC2077]
        ///vnd.collada+xml,model/vnd.collada+xml,[James_Riordon]
        ///vnd.dwf,model/vnd-dwf,[Jason_Pratt]
        ///vnd.flatland.3dml,model/vnd.flatland.3dml,[Michael_Powers]
        ///vnd.gdl,model/vnd.gdl,[Attila_Babits]
        ///vnd.gs-gdl,model/vnd.gs-gdl,[Attila_Babits]
        ///vnd.gtw,model/vnd.gtw,[Yutaka_Ozaki]
        ///vnd.moml+xml [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name,Template,Reference
        ///alternative,,[RFC2046][RFC2045]
        ///appledouble,multipart/appledouble,[Patrik_Faltstrom]
        ///byteranges,multipart/byteranges,[RFC7233]
        ///digest,,[RFC2046][RFC2045]
        ///encrypted,multipart/encrypted,[RFC1847]
        ///example,multipart/example,[RFC4735]
        ///form-data,multipart/form-data,[RFC7578]
        ///header-set,multipart/header-set,[Dave_Crocker]
        ///mixed,,[RFC2046][RFC2045]
        ///parallel,,[RFC2046][RFC2045]
        ///related,multipart/related,[RFC2387]
        ///report,multipart/report,[RFC6522]
        ///signed,multipart/signed,[RFC1847] [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string multipart {
            get {
                return ResourceManager.GetString("multipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name,Template,Reference
        ///1d-interleaved-parityfec,text/1d-interleaved-parityfec,[RFC6015]
        ///cache-manifest,text/cache-manifest,[W3C][Robin_Berjon]
        ///calendar,text/calendar,[RFC5545]
        ///css,text/css,[RFC2318]
        ///csv,text/csv,[RFC4180][RFC7111]
        ///csv-schema,text/csv-schema,[National_Archives_UK][David_Underdown]
        ///directory - DEPRECATED by RFC6350,text/directory,[RFC2425][RFC6350]
        ///dns,text/dns,[RFC4027]
        ///ecmascript - OBSOLETED in favor of application/ecmascript,text/ecmascript,[RFC4329]
        ///encaprtp,text/encaprtp,[RFC6 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name,Template,Reference
        ///1d-interleaved-parityfec,video/1d-interleaved-parityfec,[RFC6015]
        ///3gpp,video/3gpp,[RFC3839][RFC6381]
        ///3gpp2,video/3gpp2,[RFC4393][RFC6381]
        ///3gpp-tt,video/3gpp-tt,[RFC4396]
        ///BMPEG,video/BMPEG,[RFC3555]
        ///BT656,video/BT656,[RFC3555]
        ///CelB,video/CelB,[RFC3555]
        ///DV,video/DV,[RFC6469]
        ///encaprtp,video/encaprtp,[RFC6849]
        ///example,video/example,[RFC4735]
        ///H261,video/H261,[RFC4587]
        ///H263,video/H263,[RFC3555]
        ///H263-1998,video/H263-1998,[RFC4629]
        ///H263-2000,video/H263-2000,[RFC4629]
        ///H264,vide [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
    }
}
